# Generated by Django 4.0.6 on 2022-08-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_phase_phase_end_date_phase_phase_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='country',
        ),
        migrations.AddField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.country'),
        ),
        migrations.AddField(
            model_name='channel',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.strategy'),
        ),
        migrations.AddField(
            model_name='country',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.channel'),
        ),
        migrations.AddField(
            model_name='phase',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.plan'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.phase'),
        ),
    ]
