# Generated by Django 4.0.6 on 2022-08-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_plan_phase_remove_plan_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.strategy'),
        ),
        migrations.AlterField(
            model_name='country',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.channel'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.phase'),
        ),
    ]
