# Generated by Django 4.0.6 on 2022-08-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ad_country_alter_channel_strategy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='country',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='country',
            name='channel',
        ),
        migrations.CreateModel(
            name='StrategyCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='CountryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.channel')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ad')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.channel')),
            ],
        ),
    ]
