# Generated by Django 4.0.6 on 2022-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_ad_country_remove_channel_strategy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrategyCountry',
            new_name='TargetCountry',
        ),
        migrations.AddField(
            model_name='country',
            name='targetcountries',
            field=models.ManyToManyField(through='main.TargetCountry', to='main.strategy'),
        ),
    ]
