# Generated by Django 4.0.6 on 2022-08-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_strategycountry_targetcountry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='targetchannels',
            field=models.ManyToManyField(through='main.TargetChannel', to='main.targetcountry'),
        ),
        migrations.DeleteModel(
            name='CountryChannel',
        ),
        migrations.AddField(
            model_name='targetchannel',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.channel'),
        ),
        migrations.AddField(
            model_name='targetchannel',
            name='targetcountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.targetcountry'),
        ),
    ]
